import PDFDocument from 'pdfkit'

 export const generatePdf=async (data)=>{
  return new Promise((resolve,reject)=>{
  const doc=new PDFDocument({
    size:"A4",
    margin:50,
    info:{
      Author:"CogNexusAI",
      Title:data.title,
      Creator:"CogNexusAI"
    }
  })
  ///taking data into small small chunks (buffer) then we will store all in chunks array then concatenate the all chunks and send the buffer to s3 and get the pdf url to frontend
  const chunks=[]
  doc.on("data",(chunk)=>chunks.push(chunk))
  doc.on("end",()=>resolve(Buffer.concat(chunks)))
  doc.on("error",reject)
  
  // title push
  doc
    .fontSize(28)
    .text(data.title,{
      align:"center"
    })
    .fillColor("#111827")
 
   if(data.subtitle){
   doc.moveDown(0.5)
   }



 //subtitle pushed
  doc
    .fontSize(12)
    .text(data.subtitle,{
      align:"center"
    })
    .fillColor("#6B7280")

 doc.moveDown(2)  // gap of two lines


 //section is printing 

 data?.sections?.forEach(s=>{
 doc
   .fontSize(18)
   .text(s.heading)
   .fillColor("#111827")

   doc.moveDown(0.5)

   s?.points?.forEach((p)=>{
     doc
   .fontSize(12)
   .text("• "+p,{
    lineGap:5
   })
   .fillColor("#374151")

    })
    doc.moveDown()
 });
doc.moveDown()

 doc
 .fontSize(10)
 .text("Generated By CogNexusAI",{
  align:"center"
 })
 .fillColor("#9CA3AF")


doc.end()

 });
}